# spring 中所有配置文件，命令行参数等信息，都可以通过 Environment 类来获取，或者通过 @ConfigurationProperties 注解来获取
# yml 不能使用 @PropertySource 引入属性，只能用 .properties 文件
spring:
  application:
    name: SpringBoot
    description: ${spring.application.name} is my spring boot study project
  profiles:
    active: home


# Array List Set
ymlary1: [1, 2, 3]
ymlary2:
  - 1
  - 2
  - 3

# Null
ymlnull: ~          # 相当于 json 中 {"ymlnull": null}

# Date
ymldate: 2019/01/01

# Object Map
ymlobj1: {name:zhangsan,age: 20}
ymlobj2:
  key1: value1
  key2: value2


# Composite
peoples:
  - name: zhangsan
    age: 22
  - name: lisi
    age: 20
  - {name: wangwu,age: 18}


# YAML 各种字符串格式演示
# "str\nStr2"
ymlstr1: str\nStr2

# "strRow1 strRow2"   
ymlstr5: strRow1
 strRow2          # 该行前面至少有一个空格 才行，否则格式错误

# '' 中所有转义字符都不生效，除了 ' 自身
# "str b'ob\n gg"
ymlstr2: 'str b''ob\n gg'


# "" 中转义字符会生效，但是行末 \ 代表字符串的连续，前提是该 \ 不被之前的 \ 转义
# "aaabbb\ ccc\eee ddd fff "
ymlstr3: "aaa\       # 行末的 \ 代表字符串的连接 @trap 这里 \ 后面不能有任何字符，包括空格
 bbb\\               # 行末的 \ 被 \\ 转义成普通的 \ 而不具有特殊意义了
      ccc\\eee        # 子符串中间的 \ 代表转义字符
   ddd                # 不管前缀有多少个空格，最终都是一个空格
fff                   # 前面没空格，最终也是一个空格
 "                    

# "s\ntr"
ymlstr4: 's\ntr'       # 注意 \n 不转义，原样输出

# 文字块中 所有内容 原样输出
# "strRow1\nstrRow2\n"  使用文字块保留每行之间的 \n
ymlstr6: | 
 strRow1
 strRow2

# "strRow1\nstrRow2\n\n\n"  使用文字块保留每行之间的 \n，尾随空行也加入到文字块中，直到下一个字段开始
ymlstr6: |+
 strRow1
 strRow2



# "strRow1\nstrRow2"  删除文字块末尾的 \n
ymlstr8: |-
 strRow1
 strRow2

# 这里也有 >, >+, >-; 效果同 |, |+, |-
# "strRow1 strRow2\n"  使用文字块删除每行之间的 \n，但是每行之间会有一个空格
ymlstr9: >
 strRow1
 strRow2
 
# YAML 引用: 引用前面已有配置的值
ymlref3: ${a.b.c:defaultValue}    # : 后面的表示如果前面引用取不到，那么使用后面的默认值，默认值也可以使用 ${} 取引用

# YAML Anchors: 引用前面已有的配置，@trap 不仅仅是值，而是整个对象，包括子属性
ymlref1: &ref refValue
ymlref2: *ref             # 相当于 ymlref2: refValue


# 文档块：表示相当于另一个文件
---
